backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: 'index'
    media_folder: 'images'
    public_folder: './images'
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", valueField: "name", searchFields: ["name"] }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Hero", name: "hero", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "authors"
    label: "Authors"
    folder: "content/authors/authors"
    create: true
    delete: true
    format: "yml"
    identifier_field: "name"
    media_folder: "avatars"
    public_folder: "./avatars"
    editor:
      preview: false
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Bio, name: bio, widget: string }
      - { label: Featured, name: featured, widget: boolean, default: false }
      - { label: Avatar, name: avatar, widget: image }
      - { label: Social, name: social, widget: list, collapsed: false, field: { label: URL, name: url, widget: string } }